apiVersion: apps/v1
kind: Deployment
metadata:
  name: ureverse-be
  labels:
    app: ureverse-be
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ureverse-be
  template:
    metadata:
      labels:
        app: ureverse-be
        namespace: myapp
    spec:
      containers:
      - name: ureverse-be
        image: taeyeon0319/ureverse-be:kty
        ports:
        - containerPort: 8080
