apiVersion: v1
kind: Service
metadata:
  name: ureverse-be-service
spec:
  type: NodePort
  selector:
    app: ureverse-be
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31080
      protocol: TCP
